# Generated by Django 5.0.7 on 2026-06-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtransaction',
            name='medium',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
