# Generated by Django 5.0.7 on 2026-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_oauthtransaction_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtransaction',
            name='medium',
            field=models.CharField(default='web', max_length=10),
        ),
    ]
