# Generated by Django 5.0.7 on 2026-08-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_creatoruser_instagram_connected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
