# Generated by Django 5.0.7 on 2026-09-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_target_audience_businessuser_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampage',
            name='insights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
