# Generated by Django 5.0.7 on 2026-09-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_instagrampage_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampage',
            name='reach',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
