# Generated by Django 5.0.7 on 2026-09-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_instagrampage_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammedia',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
