# Generated by Django 5.0.7 on 2026-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_instagrammedia_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammedia',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
