# Generated by Django 5.0.7 on 2026-09-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_instagrammedia_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampage',
            name='media_insights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
