# Generated by Django 5.0.7 on 2026-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_instagrampage_media_insights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampage',
            name='insights_raw',
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='insights',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='media_insights',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='reach',
            field=models.JSONField(default=[]),
        ),
    ]
