# Generated by Django 5.0.7 on 2026-09-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_instagrampage_insights_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampage',
            name='insights',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='media_insights',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='reach',
            field=models.JSONField(default=list),
        ),
    ]
