# Generated by Django 5.0.7 on 2026-09-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_instagrampage_insights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrammedia',
            name='insights_raw',
        ),
    ]
