# Generated by Django 5.0.7 on 2025-12-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('requirements', models.TextField()),
                ('target_creator', models.CharField(choices=[('art', 'Art and Photography'), ('automotive', 'Automotive'), ('beauty', 'Beauty and Makeup'), ('business', 'Business'), ('diversity', 'Diversity and Inclusion'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('food', 'Food and Beverage'), ('gaming', 'Gaming'), ('health', 'Health and Wellness'), ('home', 'Home and Gardening'), ('outdoor', 'Outdoor and Nature'), ('parenting', 'Parenting and Family'), ('pets', 'Pets'), ('sports', 'Sports and Fitness'), ('technology', 'Technology'), ('travel', 'Travel'), ('videography', 'Videography')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.businessuser')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.creatoruser')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.question')),
            ],
        ),
    ]
