# Generated by Django 5.0.7 on 2026-04-30 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='due_date',
        ),
    ]
