# Generated by Django 5.0.7 on 2026-07-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_oauthtransaction_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampage',
            name='fb_page',
        ),
        migrations.CreateModel(
            name='InstagramAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_user_id', models.CharField(max_length=255, unique=True)),
                ('long_token', models.TextField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ig_auth', to='users.creatoruser')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampage',
            name='ig_auth',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ig_page', to='users.instagramauth'),
            preserve_default=False,
        ),
    ]
