# Generated by Django 5.0.7 on 2026-07-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_instagrampage_fb_page_instagramauth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='owner',
        ),
        migrations.DeleteModel(
            name='FacebookAuth',
        ),
        migrations.DeleteModel(
            name='FacebookPage',
        ),
    ]
