# Generated by Django 5.0.7 on 2026-07-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_facebookpage_owner_delete_facebookauth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatoruser',
            name='instagram_connected',
        ),
        migrations.RemoveField(
            model_name='creatoruser',
            name='youtube_connected',
        ),
    ]
