# Generated by Django 5.0.7 on 2026-08-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_instagrammedia_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
