# Generated by Django 5.0.7 on 2026-08-26 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_user_type_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessuser',
            old_name='target_audience',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='creatoruser',
            old_name='area',
            new_name='category',
        ),
    ]
