# Generated by Django 5.0.7 on 2026-08-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aspect',
            field=models.CharField(default='1:1', max_length=4),
        ),
    ]
